# Generated by Django 5.1.3 on 2024-12-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.AlterField(
            model_name='resume',
            name='parsed_data',
            field=models.JSONField(default=list),
        ),
    ]
